In [61]:
import pandas as pd
df=pd.Series([1,2,3,4],index=['a','b','c','d'])
print(df)


a    1
b    2
c    3
d    4
dtype: int64


In [62]:
##Numpy array and basics
import numpy as np


Creating array form list

In [ ]:
arr_1d=np.array([[1,2,3],[4,5,6]]) # number of rows and column should be same
print(arr_1d)

[[1 2 3]
 [4 5 6]]


In [64]:
#List vs numpy array
py_list=[1,2,3,4]
print(py_list*2)
np_array=np.array([1,2,3,4])
print(np_array*2) ##this is scaler multiplication ,element wise multiplecation
import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time:",time.time()-start)

start=time.time()
py_array=np.arange(1000000)*2
print("\n List operation time:",time.time()-start)


#NumPy me list [] se banti hai, lekin NumPy array banane ke liye np.array() ya np.arange() use karte hain — range() NumPy array nahi banata.







[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]

 List operation time: 0.15874910354614258

 List operation time: 0.009404897689819336


In [65]:
zeros=np.zeros((2,4))
print(zeros)

ones=np.ones((3,4))
print(ones)

full=np.full((5,6),7)
print(full)

random=np.random.random((5,6))
print(random)


sequence=np.arange(1,10000,2)
print(sequence)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]
[[0.38316587 0.37956918 0.5208762  0.23515313 0.7249945  0.33764755]
 [0.90636236 0.15329736 0.56123233 0.96735193 0.94974375 0.59185008]
 [0.96999172 0.377381   0.26146885 0.92065965 0.06462934 0.50670725]
 [0.12258706 0.46490761 0.47973772 0.62948291 0.49463623 0.15929719]
 [0.69957384 0.94003095 0.15962879 0.38242786 0.63018273 0.16305975]]
[   1    3    5 ... 9995 9997 9999]


In [66]:
#Difference between vector, Matrix and Tensors
#vector
vector=np.array([1,2,3,4,5,6])

print(vector)

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

tensor=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)


##properties of array
print("shape:",matrix.shape)
print("Dimentions:",matrix.ndim)
print("size:",matrix.size)
print("Dtype:",matrix.dtype)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape: (3, 3)
Dimentions: 2
size: 9
Dtype: int64


In [ ]:
##reshaping of array
arr=np.arange(12)
print(arr)
a=arr.reshape((3,4)) ##reshape into new  row's and column's
b=a.flatten() ## return the copy of origional array
c=a.ravel() ## ravel change in origional array
## transpose function to take the transpose of an array
print(a.T)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
