In [1]:
import numpy as np

sales_data = np.array([
    [120, 150, 130, 170, 160],  
    [200, 210, 190, 220, 205], 
    [90,  110, 105, 115, 100],  
    [300, 320, 310, 330, 340],
    [180, 175, 185, 190, 200]   
])

print(sales_data.shape)

print(sales_data)

(5, 5)
[[120 150 130 170 160]
 [200 210 190 220 205]
 [ 90 110 105 115 100]
 [300 320 310 330 340]
 [180 175 185 190 200]]


In [16]:
#total sale per year
print("Total sales:" ,np.sum(sales_data[:,1:],axis=0)) # if axis=0 sum will be column wise
#minimum sales per restaurant 
print("min salses per restaurant:", np.min(sales_data[:,3:],axis=1))


Total sales: [ 965  920 1025 1005]
min salses per restaurant: [160 205 100 330 190]


In [ ]:
# we can perofrrm the operations like add, mul, dot product , magnitude etc.
#