##Numpy Array operations 

In [88]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)


print("Basic Sclicing" ,arr[1:6:2]) ## here arr[row,column]

print("Negative indexing",arr[:-1])

[1 2 3 4 5 6 7 8 9]
Basic Sclicing [2 4 6]
Negative indexing [1 2 3 4 5 6 7 8]


In [89]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific element" ,arr_2d[1,2])  # to access the specific element it is only allowed in numpy
print("entire row:",arr_2d[1] )
print("Entire row" ,arr_2d[:,1]) # meaniig row to sari aaye only specific column aye 1 index wala


Specific element 6
entire row: [4 5 6]
Entire row [2 5 8]


Sorting

In [90]:
unsorted=np.array([2,5,4,6,3,2,5,6,4,3,9,8])
print("Sorted array:", np.sort(unsorted))


ar=unsorted.reshape((4,3))
print(ar)
print("Shorted 2d array columnwise:" ,np.sort(ar,axis=0))
print("Shorted 2d array Rowwise:" ,np.sort(ar,axis=1))

Sorted array: [2 2 3 3 4 4 5 5 6 6 8 9]
[[2 5 4]
 [6 3 2]
 [5 6 4]
 [3 9 8]]
Shorted 2d array columnwise: [[2 3 2]
 [3 5 4]
 [5 6 4]
 [6 9 8]]
Shorted 2d array Rowwise: [[2 4 5]
 [2 3 6]
 [4 5 6]
 [3 8 9]]


Filtering

In [91]:
number=np.arange(10)
# we can select element of the number by applying the specific condition
even_number=number[number%2==0]
print(even_number)

[0 2 4 6 8]


Filter with mask

In [92]:
print("Number greater than 5 :",number[number>5]) ## here number>5 is a mask

Number greater than 5 : [6 7 8 9]


##Fancy indexing vs np.where()

In [93]:
indices=[2,3,4]
print(number[indices])
condition_array=np.where(number>5) #this wil return a condition array
print(condition_array)
result=np.where(number>5 ,number*4,number) ## if(number>5){number*4}else{number}
print(result)

[2 3 4]
(array([6, 7, 8, 9]),)
[ 0  1  2  3  4  5 24 28 32 36]


Adding and removing data

In [94]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

combined=arr1+arr2 ##this will add the content of the arrays
#To combine fllowing operations should be done
combine=np.concatenate((arr1,arr2))
print(combine)

[1 2 3 4 5 6]


array compatibility

In [104]:
a=np.array([3,4,5])
b=np.array([1,2,3])
new_table=np.hstack((a,b))
print(new_table)
print("Compatibility check:",a.shape==b.shape)

[3 4 5 1 2 3]
Compatibility check: True


Adding new Row and column

In [96]:
origional=np.array([[1,2],[3,4],[5,6]])
new_row=np.array([5,6])
with_new_row=np.vstack((origional,new_row))
print(with_new_row)
new_cols = np.array([[7,10],
                     [8,11],
                     [9,67]])

with_new_col=np.hstack((origional,new_cols)) 
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]
 [5 6]]
[[ 1  2  7 10]
 [ 3  4  8 11]
 [ 5  6  9 67]]


Deletion in numpyarray

In [105]:
arr=np.array([1,2,3,4,5,6,7])
delete=np.delete(arr,6) ##this will return and array
print(arr)
print(delete)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
