In [8]:
import numpy as np
import matplotlib.pyplot as plt

#Data structure:[restaurant_id ,2021,2022,2023,2024]
sales_data = np.array([
    [1,120, 150, 130, 170, 160],  #paradise birayani
    [2,200, 210, 190, 220, 205],  # Beijing Bites
    [3,90,  110, 105, 115, 100],  #Pizza Hub
    [4,300, 320, 310, 330, 340],  #Burger Bos
    [5,180, 175, 185, 190, 200]   #Chai code
])

print(sales_data.shape)

print(sales_data)

(5, 6)
[[  1 120 150 130 170 160]
 [  2 200 210 190 220 205]
 [  3  90 110 105 115 100]
 [  4 300 320 310 330 340]
 [  5 180 175 185 190 200]]


In [19]:
#data of first three restorant
print(" Sample data for 1st 3 restau",sales_data[:3,1:])
#total sale per year
print(np.sum(sales_data ,axis=0)) #if axis 0 sum column wise
#minimum sales per restaurant 
print("min salses per restaurant:", np.min(sales_data[:,3:],axis=1))

#maximum sale per year
print("maximum sale per year",np.max(sales_data[:,1:] ,axis=0))

#average sale per restautant
avg_sale=np.mean(sales_data[:,1:],axis=1)
print("Avg_sale",avg_sale)

#cumulative sales
cumsum=np.cumsum(sales_data[:,1:],axis=1)
print("cumsum",cumsum)
print("cumsum mean",np.mean(cumsum[:,:],axis=0))

   


 Sample data for 1st 3 restau [[120 150 130 170 160]
 [200 210 190 220 205]
 [ 90 110 105 115 100]]
[  15  890  965  920 1025 1005]
min salses per restaurant: [130 190 100 310 185]
maximum sale per year [300 320 310 330 340]
Avg_sale [146. 205. 104. 320. 186.]
cumsum [[ 120  270  400  570  730]
 [ 200  410  600  820 1025]
 [  90  200  305  420  520]
 [ 300  620  930 1260 1600]
 [ 180  355  540  730  930]]
cumsum mean [178. 371. 555. 760. 961.]


In [20]:
# we can perofrrm the operations like add, mul, dot product , magnitude etc.
#vertorize method in numpy
restaurant_types=np.array(['biryani','chinese','pizza','burger','cafe'])
vectorized_upper =np.vectorize(str.upper);
print("vectorized Upper", vectorized_upper(restaurant_types))

vectorized Upper ['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']


1. Vectorization = How the operation is executed

Vectorization means NumPy performs operations on the entire array at once using optimized C code instead of a Python loop.

2. Broadcasting = How shapes are made compatible

Broadcasting means NumPy automatically expands a smaller array (or scalar) to match a larger array's shape.
So conceptually:
[1, 2, 3, 4]
*
[2, 2, 2, 2]
but physically in memory there is only:
arr = [1, 2, 3, 4]
scalar = 2